stages:
  - build
  - test
  - artifact

compile_course_plan:
  image: aergus/latex
  stage: artifact
  only:
    - master
  script:
    - cd plans_2018-2019
    - make
  artifacts:
    expire_in: 10y
    paths:
      - plans_2018-2019/article.pdf

compile_slides:
  image: aergus/latex
  stage: artifact
  only:
    - master
  script:
    - cd lectures
    - make
    - cd ../tutorials
    - make
  artifacts:
    expire_in: 10y
    paths:
      - lectures/lecture*/lecture*.pdf
      - tutorials/tutorial*/lecture.pdf

compile_slides_for_relevant_branches:
  image: aergus/latex
  stage: artifact
  only:
    changes:
      - tutorials/**/*
      - lectures/**/*
  except:
    - master
  script:
    - cd lectures
    - make
    - cd ../tutorials
    - make
  artifacts:
    expire_in: 1w
    paths:
      - lectures/lecture*/lecture*.pdf
      - tutorials/tutorial*/lecture*.pdf

lecture_texstyle:
  image: aergus/latex
  stage: build
  script:
    - cd lectures
    - ./checktex

lecture_pycodestyle:
  image: python:3.7-alpine
  stage: build
  script:
    - apk add --no-cache git
    - pip install pipenv
    - pipenv install
    - cd lectures
    - pipenv run pycodestyle **/code/*.py


lab_codestyle:
  image: python:3.7-alpine
  stage: build
  script:
    - apk add --no-cache git
    - pip install pipenv
    - pipenv install
    - cd implementation
    - pipenv run codestyle
    - cd ../analysis
    - pipenv run codestyle

lab_generator:
  image: python:3.7-alpine
  stage: artifact
  only:
    - master
  script:
    - apk add --no-cache git
    - pip install pipenv
    - pipenv install
    - pipenv run generator
  artifacts:
    expire_in: 10y
    paths:
      - implementation/output/**/*

lab_tests:
  image: python:3.7-alpine
  stage: test
  only:
    changes:
      - implementation/**/*
  script:
    - apk add --no-cache git
    - pip install pipenv
    - pipenv install
    - pipenv run generator
    - pipenv run tests
